### ISSUE TITLE
[Checkers] Cannot import the class "Rules"

### ISSUE THREAD

**Issue by adelshb** [seoulai/gym#13]
Hi! 

I'm currently having some issues with the checkers environment. I'm trying to make my own agent and I need the function "get_valid_moves" which is defined in the class Rules. However, I can't load the needed package. I have the following error:

```
>>> from seoulai_gym.envs.checkers.rules import Rules
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Rules'
```

Thanks a lot!
a

**Comment by martinkersner** [comment]
@adelshb From where do you try to include it?

**Comment by adelshb** [comment]
Thanks for your reply. I used pip to install seoulai-gym so it should work anywhere I run python locally. I don't think it is an environment problem either as the other imports from saoulai-gym work fine.

**Comment by martinkersner** [comment]
@adelshb The problem is that pip package is not always up to date. I will make new package today. In the mean time you can access `get_valid_moves` with the following snippet.

```python
>>> from seoulai_gym.envs.checkers.rules import get_valid_moves
>>> help(get_valid_moves)
Help on function get_valid_moves in module seoulai_gym.envs.checkers.rules:

get_valid_moves(board_list:List[List[seoulai_gym.envs.checkers.base.Piece]], from_row:int, from_col:int) -> List[Tuple[int, int]]
    Generate valid moves for given position with respect to the current state of game.

    Args:
        board_list: Information about positions of pieces.
        from_row: Row of board of piece location.
        from_col: Column of board of piece location.

    Returns:
        List of (row, column) tuples representing valid moves for given piece location at current
        state of board.
```
